---
title: gcWorld Modifications
timezone: UTC
collections:
  downloads:
    title: Downloads
    output: true
    sort: updated
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
      type: downloads
    values:
      layout: download
      menu: /downloads/index.html
      menu_en: /downloads/en/index.html
  - scope:
      path: ''
      type: posts
    values:
      menu: /blog.html
      menu_en: /blog_en.html
email: info@gcmods.de
description: 'gcWorld Modifications bietet kostenlose Erweiterungen für den Omnibussimulator OMSI und LOTUS.

'
reCaptcha:
    enabled: true
    siteKey: "6LdfFcUSAAAAABjim_wfeAZCrDDGNbnnPLq50PJQ"
    secret: "gfsQFwVc+c+9YjVoX3PAs/1HryM44UONvReu34dBUux/g24BNHmvg925rJG8saE/UOpb9s0Kw8HbTdk+UHeyNwDW1R4IBFTb+mpAJ4g5rKyidCO6jSANTgM/8FzzqQ9JaFeVX1rNSUYHXl5KIPkCAajDtuGJA8MLVtv6+QIFhDM="

include: [_redirects]
lang: 'de'
baseurl: ''
url: 'www.gcmods.de'
twitter_username: 
github_username: gcWorld
piwik: false
google_analytics: false
google_ads: false
tracking_pixel: false
fathom: false
umami: true
cookies: false
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- themes
- content
disqus: gcmods

m:
  de:
    home:
      name: "Home"
      url: "/"
    about:
      name: "Blog"
      url: "/blog"
    download:
      name: "Downloads"
      url: "/downloads/"
    contact:
      name: "Kontakt"
      url: "/kontakt"
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "Blog"
      url: "/blog_en"
    download:
      name: "Downloads"
      url: "/downloads/"
    contact:
      name: "Contact"
      url: "/contact"
