---
title: gcWorld Modifications
timezone: UTC
collections:
  downloads:
    title: Downloads
    output: true
    sort: updated
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ''
      type: downloads
    values:
      layout: download
      menu: downloads
email: info@gcmods.de
description: 'gcWorld Modifications bietet kostenlose Erweiterungen für den Omnibussimulator OMSI 1 und OMSI 2.

'

include: [_redirects]
lang: 'de'
baseurl: ''
url: 'www.gcmods.de'
twitter_username: gcMods
github_username: gcWorld
google_analytics: true
google_ads: false
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- themes
- content
disqus: gcmods

m:
  de:
    home:
      name: "Home"
      url: "/"
    about:
      name: "Blog"
      url: "/blog"
    download:
      name: "Downloads"
      url: "/downloads/"
    contact:
      name: "Kontakt"
      url: "/kontakt"
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "Blog"
      url: "/blog_en"
    download:
      name: "Downloads"
      url: "/downloads/"
    contact:
      name: "Contact"
      url: "/contact"
