defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
baseURL = 'https://hugo.gcmods.de/'
title = 'gcWorld Modifications'
theme = ['gcmods']
sectionPagesMenu = "main"
[languages]
  [languages.de]
    contentDir = 'content/de'
    languageName = 'Deutsch'
    weight = 1
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 2

[Params]
  google_ads = true
